
?start: (instr|comment|loop)*   -> start

?loop: "[" (instr|comment|loop)* "]"  -> loop

?instr: "+"                 -> incr
     | "-"                  -> decr
     | ">"                  -> ptri
     | "<"                  -> ptrd
     | ","                  -> inpt
     | "."                  -> outp

?comment: LETTER | DIGIT    -> ignore

%import common.LETTER
%import common.DIGIT
%import common.WS_INLINE

%ignore WS_INLINE
